#!/bin/bash

cp ${PROJECT_ROOT}/.docksal/settings.local.php ${PROJECT_ROOT}/web/sites/default/settings.local.php

fin up
fin exec "composer install"
cd web
chmod 777 sites/default/settings.php
fin drush si config_installer config_installer_sync_configure_form.sync_directory=../config/sync --account-pass=admin -y